# -*- coding: utf-8 -*-
"""Tesseract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-aJcqhCueQmlNSoUWv--CCFWNGC3OmO-
"""



def readText(path):
  import numpy as np
  import cv2 as cv
  import os
  import pytesseract
  import os

  img_read = cv.imread(path, cv.IMREAD_GRAYSCALE)
  extractedInformation = pytesseract.image_to_string(img_read)
  return extractedInformation

print(readText("/Users/mentxaka/Documents/Y - Trabajo/TK - Vision Artificial/Imagenes/matriculas/imagen_4.png"))