# -*- coding: utf-8 -*-
"""Tesseract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-aJcqhCueQmlNSoUWv--CCFWNGC3OmO-
"""



def readTesseract(path):
  import numpy as np
  import cv2 as cv
  import os
  import pytesseract
  import os

  img_read = cv.imread(path, cv.IMREAD_GRAYSCALE)
  extractedInformation = pytesseract.image_to_string(img_read)
  return extractedInformation

def prepareReadEasy():
  import easyocr
  return easyocr.Reader(['en']) # this needs to run only once to load the model into memory
  
def readEasy(reader, path):
  return reader.readtext(path)